services:
  govorun:
    container_name: govorun_app
    image: ghcr.io/for9653960484/govorun_ai_assist:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
